services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Controllers
    Webberdoo\InstallerBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
        public: true

    # Services
    Webberdoo\InstallerBundle\Service\UserEntityDetector:
        arguments:
            $entities: '%installer.entities%'

    Webberdoo\InstallerBundle\Service\SystemRequirementsChecker:
        arguments:
            $requirements: '%installer.requirements%'
            $projectDir: '%kernel.project_dir%'

    Webberdoo\InstallerBundle\Service\EnvFileWriter:
        arguments:
            $projectDir: '%kernel.project_dir%'

    Webberdoo\InstallerBundle\Service\DatabaseConfigWriter:
        arguments:
            $dbConfig: '%installer.database%'

    Webberdoo\InstallerBundle\Service\SchemaInstaller:
        arguments:
            $entities: '%installer.entities%'
            $dbConfig: '%installer.database%'
            $projectDir: '%kernel.project_dir%'

    Webberdoo\InstallerBundle\Service\AdminUserCreator:
        arguments:
            $adminConfig: '%installer.admin_user%'
            $dbConfig: '%installer.database%'
            $projectDir: '%kernel.project_dir%'

    Webberdoo\InstallerBundle\Service\AppConfigWriter:
        arguments:
            $appConfig: '%installer.app_config%'
            $installMarkerPath: '%installer.install_marker_path%'

    Webberdoo\InstallerBundle\Service\InstallationStatusChecker:
        arguments:
            $adminConfig: '%installer.admin_user%'
            $em: '@doctrine.orm.entity_manager'
